# Generated by Django 2.1.7 on 2019-04-07 17:39

from django.db import migrations, models
import django.db.models.deletion
import pinus_key.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinusGenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(max_length=150)),
                ('summary', models.CharField(max_length=5000)),
                ('old_cones', models.BooleanField()),
                ('twig_texture', models.BooleanField()),
                ('fire_resilience', models.BooleanField()),
                ('distribution', models.CharField(choices=[(pinus_key.models.Distribution('Northern states'), 'Northern states'), (pinus_key.models.Distribution('Middle states'), 'Middle states'), (pinus_key.models.Distribution('south'), 'south'), (pinus_key.models.Distribution('northern and middle states'), 'northern and middle states'), (pinus_key.models.Distribution('middle and southern states'), 'middle and southern states')], max_length=60)),
                ('needle_length', models.CharField(choices=[(pinus_key.models.NeedleLength('2-3'), '2-3'), (pinus_key.models.NeedleLength('2-4'), '2-4'), (pinus_key.models.NeedleLength('3-5'), '3-5'), (pinus_key.models.NeedleLength('3-6'), '3-6'), (pinus_key.models.NeedleLength('4-6'), '4-6'), (pinus_key.models.NeedleLength('4-8'), '4-8'), (pinus_key.models.NeedleLength('5-11'), '5-11'), (pinus_key.models.NeedleLength('6-9'), '6-9'), (pinus_key.models.NeedleLength('8-18'), '8-18')], max_length=60)),
                ('needle_count', models.IntegerField(choices=[(pinus_key.models.NeedleCount(2), 2), (pinus_key.models.NeedleCount(3), 3), (pinus_key.models.NeedleCount(5), 5)])),
                ('cone_length', models.CharField(choices=[(pinus_key.models.ConeLength('longer than three inches'), 'longer than three inches'), (pinus_key.models.ConeLength('shorter than three inches'), 'shorter than three inches'), (pinus_key.models.ConeLength('size can be plus or minus 3 inches'), 'size can be plus or minus 3 inches')], max_length=60)),
                ('cone_shape', models.CharField(choices=[(pinus_key.models.ConeShape('round'), 'round'), (pinus_key.models.ConeShape('Longer than Wide'), 'Longer than Wide'), (pinus_key.models.ConeShape('Wider than long'), 'Wider than long'), (pinus_key.models.ConeShape('larger axis varies'), 'larger axis varies')], max_length=60)),
                ('cone_prickles', models.CharField(choices=[(pinus_key.models.ConePrickles('thin'), 'thin'), (pinus_key.models.ConePrickles('lacking'), 'lacking'), (pinus_key.models.ConePrickles('thin to lacking'), 'thin to lacking'), (pinus_key.models.ConePrickles('stout'), 'stout')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PinusKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_a', models.CharField(max_length=400)),
                ('characteristic_b', models.CharField(max_length=400)),
                ('object_id', models.PositiveIntegerField()),
                ('child_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType')),
                ('child_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pinus_key.PinusKey')),
            ],
        ),
    ]
