# Generated by Django 2.1.7 on 2019-04-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinus_key', '0001_initial'),
    ]

    operations = [
    ]
