# Generated by Django 2.1.7 on 2019-04-07 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinus_key', '0002_auto_20190407_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinusgenus',
            old_name='summary',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pinuskey',
            old_name='object_id',
            new_name='object_id_a',
        ),
        migrations.AddField(
            model_name='pinuskey',
            name='object_id_b',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pinuskey',
            name='characteristic_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pinuskey',
            name='characteristic_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pinuskey',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pinuskey',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pinus_key.PinusKey'),
        ),
    ]
