# Generated by Django 2.1.7 on 2019-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinus_key', '0003_auto_20190407_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinusgenus',
            name='fire_resilience',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pinusgenus',
            name='twig_texture',
            field=models.BooleanField(null=True),
        ),
    ]
